### ISSUE TITLE
Artillery script is not displayed

### ISSUE THREAD

**Issue by damimj** [rupeshmore/dakiya#1]
Hi, I'm trying your tool but when you select Artillery, the pop up with the script is not displayed. Browser's console show this:

```
VM269:2 Uncaught SyntaxError: Unexpected token n in JSON at position 19
    at JSON.parse (<anonymous>)
    at https://dakiya.now.sh/js/dakiya.js:331:49
    at Array.forEach (native)
    at artillery (https://dakiya.now.sh/js/dakiya.js:272:9)
    at convertPostman (https://dakiya.now.sh/js/dakiya.js:92:7)
    at HTMLSelectElement.onchange (https://dakiya.now.sh/:82:99)
    at Object.trigger (https://dakiya.now.sh/js/jquery-2.2.3.min.js:4:4887)
    at HTMLSelectElement.<anonymous> (https://dakiya.now.sh/js/jquery-2.2.3.min.js:4:5389)
    at Function.each (https://dakiya.now.sh/js/jquery-2.2.3.min.js:2:2861)
    at n.fn.init.each (https://dakiya.now.sh/js/jquery-2.2.3.min.js:2:845)
```
 the script for Gatling is displayed without problems

**Comment by rupeshmore** [comment]
Hi damimj,
First thanks for trying out Dakiya and logging an issue.
As per the error log, the tool is not able to parse the body for the postman collection as JSON. Maybe the body is not JSON. whereas the headers are content-type is 'application/json'.

If you can share your collection with masked hostname and variables and whatever feels to hide or mask it will be good, this will help me to reproduce the error and help close the bug.

In the meanwhile, I will try to reproduce and fix the issue at my end.

**Comment by rupeshmore** [comment]
@damimj 
Are you able to confirm if the **request** has _headers_ `application/json` and the body is not `json`(enclosed in curly braces {} )?
I have a fix for the above bug, however, need some confirmation before I commit the fix. 
Also, can you construct a dummy collection based on your collection where the tool is displaying the error?

**Comment by damimj** [comment]
Hi @rupeshmore sorry for my delay.
Yes, it was a body with a typo in my collection. I fixed and Artillery option now shows the pop-up. Maybe an error message saying that something is wrong in the collection could warn Users of what's going on. Thanks

**Comment by rupeshmore** [comment]
Hi @damimj.
Thanks for the response. Noted your suggestion, I will try to have better error handling with messages as an enhancement in the future releases.
